version: '3'
services:
  website:
    build: './Website'
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  
  camera-controller:
    build: './Camera-Controller'
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
  photo-mod:
    build: './Photo-Mod'
  redis:
    image: "redis:alpine"