version: '3'
services:
  admin-website:
    build: './Admin-Website'
    ports:
      - "5000:5000"
    volumes:
      - ./Admin-Website:/share
    networks:
      - studio
    environment:
      - "PYTHONUNBUFFERED=1"
    depends_on:
      - camera-controller
      - countdown-service
      - photo-album
  
  website:
    build: './Website'
    ports:
     - "5001:5000"
    volumes:
     - ./Website:/share
    hostname: 'web'
    networks:
      - studio
    depends_on:
      - camera-controller
      - countdown-service
      - photo-album
    environment:
      - "PYTHONUNBUFFERED=1"
  
  photo-album:
    build: './Photo-Album'
    ports:
      - "5011:5000"
    volumes:
      - "./photos:/photos"
    networks:
      - studio
    depends_on:
      - countdown-service
    environment:
      - "PYTHONUNBUFFERED=1"

  countdown-service:
    build: './Countdown-Service'
    ports:
      - "5010:5000"
    networks:
      - studio
    environment:
      - "PYTHONUNBUFFERED=1"
  
  camera-controller:
    build: './Camera-Controller'
    ports:
      - "5002:5000"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
      - ./photos:/photos
      - ./Camera-Controller:/share
      - ./logo:/logo
    hostname: 'cam'
    networks:
      - studio
    environment:
      - "PYTHONUNBUFFERED=1"

networks:
  studio:
    driver: bridge
