version: '3'
services:
  admin-website:
    build: './Admin-Website'
    ports:
      - "5000:5000"
    volumes:
     - ./Admin-Website:/share
  
  website:
    build: './Website'
    ports:
     - "5001:5000"
    volumes:
     - ./Website:/share
    hostname: 'web'
    networks:
      - studio
    depends_on:
      - camera-controller
      - photo-mod
      - countdown-service
  
  countdown-service:
    build: './Countdown-Service'
    ports:
      - "5010:5000"
    networks:
      - studio

  countdown-website:
    build: './Countdown-Website'
    ports:
      - "5004:5000"
    hostname: 'countdown'
    networks:
      - studio
    depends_on:
      - website
  
  camera-controller:
    build: './Camera-Controller'
    ports:
     - "5002:5000"
    volumes:
     - .:/share
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
      - ./photos:/photos
    hostname: 'cam'
    networks:
      - studio

  photo-mod:
    build: './Photo-Mod'
    volumes:
     - .:/share
    ports:
      - 5003:5000
    hostname: 'mod'
    networks:
      - studio

networks:
  studio:
    driver: bridge
