version: '3'
services:
  website:
    build: './Website'
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  camera-controller:
    build: './Camera-Controller'
  redis:
    image: "redis:alpine"