version: '3'
services:
  admin-website:
    build: './Admin-Website'
    ports:
      - "5000:5000"
    volumes:
     - ./Admin-Website:/share
  
  website:
    build: './Website'
    ports:
     - "5001:5000"
    volumes:
     - ./Website:/share
    hostname: 'web'
    networks:
      - studio
    depends_on:
      - camera-controller
      - countdown-service
  
  countdown-service:
    build: './Countdown-Service'
    ports:
      - "5010:5000"
    networks:
      - studio
  
  camera-controller:
    build: './Camera-Controller'
    ports:
      - "5002:5000"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/udev:/run/udev:ro
      - ./photos:/photos
      - .:/share
    hostname: 'cam'
    networks:
      - studio

networks:
  studio:
    driver: bridge
